# [DURABLE] Asset-pipeline orchestration retained when merged into franka_web.
# Copyright 2026 The multipanda_ros2 Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Orchestrate deterministic ghost frontend asset generation."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import shutil

from ament_index_python.packages import get_package_share_directory

from .mesh_convert import convert_mesh
from .urdf_export import (
    collect_mesh_references,
    description_share_directory,
    expand_dual_urdf,
    sha256_bytes,
    XACRO_ARGS,
    XACRO_RELATIVE_PATH,
)


MANIFEST_SCHEMA = 'franka.ghost.manifest/1'
VENDOR_SOURCE = Path('/usr/share/javascript/three/three.min.js')
VENDOR_VERSION = '111+dfsg1-3'
VENDOR_SHA256 = 'd4c5322f72bc86b8ffe7e2a3d1652c0999e4c449342770418cf08b43dc66fbce'
MAX_ASSET_BYTES = 12 * 1024 * 1024


@dataclass(frozen=True)
class PrepResult:
    """Summary of an asset preparation run."""

    regenerated: bool
    asset_bytes: int
    mesh_count: int


def default_package_root() -> Path:
    """Return the source package root, including under a symlink install."""
    return Path(__file__).resolve().parents[1]


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def _resolve_package_uri(uri: str, description_share: Path) -> Path:
    prefix = 'package://'
    if not uri.startswith(prefix):
        raise ValueError(f'not a package URI: {uri}')
    package_and_path = uri[len(prefix):].split('/', 1)
    if len(package_and_path) != 2 or not all(package_and_path):
        raise ValueError(f'invalid package URI: {uri}')
    package, relative = package_and_path
    if package == 'franka_description':
        return description_share / relative
    return Path(get_package_share_directory(package)) / relative


def _vendor_markdown(source: Path) -> str:
    return (
        '# three.js vendor record\n\n'
        'Generated by `franka_ghost_prep`; `web/vendor/` is gitignored.\n\n'
        '- Stage 0 choice: A — distro package, kept out of git\n'
        f'- Source: `{source}`\n'
        f'- Package version: `{VENDOR_VERSION}`\n'
        f'- SHA-256: `{VENDOR_SHA256}`\n'
        '- License: MIT (three.js); supplied by Ubuntu package `libjs-three`\n'
    )


def _prepare_vendor(package_root: Path, vendor_source: Path) -> None:
    source = Path(vendor_source)
    if not source.is_file():
        raise FileNotFoundError(f'approved three.js build not found: {source}')
    actual_hash = _file_sha256(source)
    if actual_hash != VENDOR_SHA256:
        raise ValueError(
            f'three.js SHA-256 mismatch: expected {VENDOR_SHA256}, got {actual_hash}'
        )
    vendor = package_root / 'web/vendor'
    vendor.mkdir(parents=True, exist_ok=True)
    destination = vendor / 'three.min.js'
    if not destination.is_file() or _file_sha256(destination) != actual_hash:
        shutil.copyfile(source, destination)
    record = _vendor_markdown(source)
    record_path = vendor / 'VENDOR.md'
    if not record_path.is_file() or record_path.read_text(encoding='utf-8') != record:
        record_path.write_text(record, encoding='utf-8')


def _inputs(
    mesh_references: tuple[str, ...],
    description_share: Path,
) -> tuple[dict[str, Path], dict[str, str]]:
    paths = {
        uri: _resolve_package_uri(uri, description_share)
        for uri in mesh_references
    }
    for uri, path in paths.items():
        if not path.is_file():
            raise FileNotFoundError(f'mesh for {uri} not found: {path}')
    hashes = {uri: _file_sha256(path) for uri, path in paths.items()}
    return paths, hashes


def _manifest_inputs(
    urdf_hash: str,
    mesh_hashes: dict[str, str],
    mesh_outputs: dict[str, str],
) -> dict:
    return {
        'schema': MANIFEST_SCHEMA,
        'generated_from': {
            'xacro': f'franka_description/{XACRO_RELATIVE_PATH.as_posix()}',
            'args': XACRO_ARGS,
            'urdf_sha256': urdf_hash,
            'mesh_sha256': mesh_hashes,
        },
        'urdf': 'model.urdf',
        'meshes': mesh_outputs,
    }


def _output_hashes(
    asset_root: Path,
    manifest: dict,
    expected_paths: set[str],
) -> dict[str, str] | None:
    output_hashes = manifest.get('asset_sha256')
    if not isinstance(output_hashes, dict) or set(output_hashes) != expected_paths:
        return None
    for relative, expected in output_hashes.items():
        path = asset_root / relative
        if not path.is_file() or _file_sha256(path) != expected:
            return None
    return output_hashes


def _can_skip(asset_root: Path, expected: dict) -> bool:
    manifest_path = asset_root / 'manifest.json'
    if not manifest_path.is_file():
        return False
    try:
        existing = json.loads(manifest_path.read_text(encoding='utf-8'))
    except (json.JSONDecodeError, OSError):
        return False
    for key in ('schema', 'generated_from', 'urdf', 'meshes'):
        if existing.get(key) != expected.get(key):
            return False
    expected_paths = {'model.urdf'}
    for metadata_path in expected['meshes'].values():
        expected_paths.add(metadata_path)
        expected_paths.add(metadata_path.removesuffix('.json') + '.bin')
    return _output_hashes(asset_root, existing, expected_paths) is not None


def _asset_size(asset_root: Path) -> int:
    return sum(path.stat().st_size for path in asset_root.rglob('*') if path.is_file())


def prepare_assets(
    package_root: Path,
    description_share: Path | None = None,
    vendor_source: Path = VENDOR_SOURCE,
) -> PrepResult:
    """Generate the URDF, mesh assets, manifest, and approved vendor file."""
    root = Path(package_root).resolve()
    share = Path(description_share or description_share_directory()).resolve()
    _prepare_vendor(root, Path(vendor_source))

    urdf_text = expand_dual_urdf(share)
    urdf_bytes = urdf_text.encode('utf-8')
    urdf_hash = sha256_bytes(urdf_bytes)
    mesh_references = collect_mesh_references(urdf_text)
    mesh_paths, mesh_hashes = _inputs(mesh_references, share)
    mesh_outputs = {
        uri: f'meshes/{path.stem}.ghostmesh.json'
        for uri, path in mesh_paths.items()
    }
    expected = _manifest_inputs(urdf_hash, mesh_hashes, mesh_outputs)

    asset_root = root / 'web/assets'
    if _can_skip(asset_root, expected):
        size = _asset_size(asset_root)
        if size > MAX_ASSET_BYTES:
            raise ValueError(
                f'generated asset payload is {size} bytes; '
                f'limit is {MAX_ASSET_BYTES}'
            )
        return PrepResult(False, size, len(mesh_outputs))

    mesh_root = asset_root / 'meshes'
    mesh_root.mkdir(parents=True, exist_ok=True)
    (asset_root / 'model.urdf').write_bytes(urdf_bytes)
    generated_files = ['model.urdf']
    for uri, source_path in mesh_paths.items():
        source_label = uri.removeprefix('package://')
        converted = convert_mesh(source_path, mesh_root, source_label)
        generated_files.extend(
            [
                f'meshes/{converted.metadata_path.name}',
                f'meshes/{converted.binary_path.name}',
            ]
        )

    manifest = dict(expected)
    manifest['asset_sha256'] = {
        relative: _file_sha256(asset_root / relative)
        for relative in sorted(generated_files)
    }
    (asset_root / 'manifest.json').write_text(
        json.dumps(manifest, indent=2, separators=(',', ': ')) + '\n',
        encoding='utf-8',
    )
    size = _asset_size(asset_root)
    if size > MAX_ASSET_BYTES:
        raise ValueError(
            f'generated asset payload is {size} bytes; limit is {MAX_ASSET_BYTES}'
        )
    return PrepResult(True, size, len(mesh_outputs))
